name: run eventos.sh

on:
  workflow_dispatch:
  
  schedule:
    # Corre cada 2h entre las 8 y las 23
    - cron: '0 8-23/2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push
      contents: write
      
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages and playwright
        run: |
          sudo apt-get install pandoc -y
          sudo apt-get install curl -y
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium
          
      - name: Set up permissions
        run: |
          chmod +x eventos.sh
          chmod +x generador_html.sh
        
      - name: execute py script # run main.py
        run: python getElcanoWeb.py
      
      - name: Run script
        run: /bin/bash ./eventos.sh
          
      - name: pull changes
        run: git pull origin main
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update list" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
